[mgr]
# show hidden files
show_hidden = true
# show directories first
show_dir_first = true
# file sorting method
sort_by = "mtime"

[opener]
edit = [
  { run = 'nvim "$@"', block = true }
]

[preview]
max_width = 2400
max_height = 3600
