# available keybinding maps: https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings/Custom_Keybindings.md
# general config doc: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

keybinding:
  universal:
    confirmInEditor: <c-s>
    filteringMenu: <c-f>
